### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by pooley92** [hardwario/twr-lora-tester-lcd-gps-ttnmapper#1]
Can we get the latest bcf-sdk/bcl/src/bc_cmwx1zzabz.c into new firmware. Also big clown Lora is still branded in the old firmware.

**Comment by hubmartin** [comment]
Thanks I've fixed text in the menu
https://github.com/hardwario/bcf-lora-tester-lcd-gps-ttnmapper/blob/master/app/application.c#L99

I do not understand this, can you elaborate more?
`Can we get the latest bcf-sdk/bcl/src/bc_cmwx1zzabz.c into new firmware.`
If you would like latest SDK, just call `make update` and `sdk/` git submodule folder is updated to the latest version.

https://tower.hardwario.com/en/latest/firmware/basic-overview/?highlight=%22make%20update%22#sdk-integration
